# Generated by Django 3.1.4 on 2021-11-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brand',
            table=None,
        ),
        migrations.AlterModelTable(
            name='customers',
            table=None,
        ),
        migrations.AlterModelTable(
            name='orderdetails',
            table=None,
        ),
        migrations.AlterModelTable(
            name='orders',
            table=None,
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
