# Generated by Django 3.1.4 on 2021-11-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211124_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='createdate',
            field=models.DateField(db_column='CreateDate', default='2021-11-25'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.FileField(db_column='IMG', max_length=200, upload_to=''),
        ),
    ]
