# Generated by Django 3.1.4 on 2021-12-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211125_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='orderid',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='productid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='customerid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brandid',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='Orderdetails',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
