# Generated by Django 3.1.4 on 2021-12-07 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_auto_20211207_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('default_address', models.CharField(blank=True, db_column='Default Address', max_length=45, null=True)),
                ('shippingaddress', models.CharField(blank=True, db_column='ShippingAddress', max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('brandname', models.CharField(db_column='BrandName', max_length=200)),
                ('branddes', models.CharField(blank=True, db_column='BrandDes', max_length=2000, null=True)),
                ('img', models.CharField(blank=True, db_column='IMG', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartid', models.AutoField(db_column='CartID', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('carttotal', models.FloatField(db_column='CartTotal')),
                ('cartnum', models.CharField(blank=True, db_column='Cartnum', max_length=45, null=True)),
                ('typecart', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.AutoField(db_column='OrderID', primary_key=True, serialize=False)),
                ('orderaddress', models.CharField(blank=True, db_column='OrderAddress', max_length=500, null=True)),
                ('username', models.CharField(max_length=200)),
                ('orderdate', models.DateField(blank=True, db_column='OrderDate', default='2021-12-07')),
                ('orderstatus', models.CharField(blank=True, db_column='OrderStatus', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('productcode', models.CharField(blank=True, db_column='ProductCode', max_length=200, null=True)),
                ('name', models.CharField(db_column='Name', max_length=200)),
                ('price', models.FloatField(db_column='Price')),
                ('img', models.FileField(db_column='IMG', max_length=200, upload_to='')),
                ('description', models.CharField(blank=True, db_column='Description', max_length=2000, null=True)),
                ('stock', models.IntegerField(db_column='Stock')),
                ('createdate', models.DateField(db_column='CreateDate', default='2021-12-07')),
                ('brandname', models.ForeignKey(db_column='BrandName', on_delete=django.db.models.deletion.DO_NOTHING, to='core.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('orderid', models.IntegerField(db_column='OrderID')),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('price', models.FloatField(db_column='Price')),
                ('productname', models.ForeignKey(db_column='ProductName', on_delete=django.db.models.deletion.DO_NOTHING, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cartdetails',
            fields=[
                ('deltailsid', models.AutoField(db_column='DeltailsID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField(db_column='Price')),
                ('username', models.CharField(max_length=200)),
                ('productname', models.ForeignKey(db_column='ProductName', on_delete=django.db.models.deletion.DO_NOTHING, to='core.product')),
            ],
        ),
    ]
