# Generated by Django 3.1.4 on 2021-12-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211211_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetails',
            name='img',
            field=models.FileField(db_column='IMG', default='', max_length=200, upload_to=''),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='img',
            field=models.FileField(db_column='IMG', default='', max_length=200, upload_to=''),
        ),
    ]
