# Generated by Django 3.1.4 on 2021-12-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211211_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='productname',
            field=models.CharField(db_column='ProductName', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderdate',
            field=models.DateField(blank=True, db_column='OrderDate', default='2021-12-13'),
        ),
        migrations.AlterField(
            model_name='product',
            name='createdate',
            field=models.DateField(db_column='CreateDate', default='2021-12-13'),
        ),
    ]
