# Generated by Django 3.1.4 on 2021-12-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211213_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='img',
            field=models.FileField(blank=True, db_column='IMG', max_length=200, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderdate',
            field=models.DateField(blank=True, db_column='OrderDate', default='2021-12-14'),
        ),
        migrations.AlterField(
            model_name='product',
            name='createdate',
            field=models.DateField(db_column='CreateDate', default='2021-12-14'),
        ),
    ]
