# Generated by Django 3.1.4 on 2021-12-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211226_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.FileField(db_column='IMG', default='placeholder.png', max_length=200, upload_to=''),
        ),
    ]
