# Generated by Django 3.2.9 on 2022-01-04 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220103_0708'),
        ('core', '0019_auto_20220103_0732'),
    ]

    operations = [
    ]
