# Generated by Django 3.1.4 on 2022-03-25 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20220325_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetails',
            name='cartid',
            field=models.ForeignKey(db_column='CartID', default=-1, on_delete=django.db.models.deletion.CASCADE, to='core.cart'),
        ),
        migrations.AlterField(
            model_name='cartdetails',
            name='productcode',
            field=models.ForeignKey(db_column='ProductCode', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='orderid',
            field=models.ForeignKey(db_column='OrderID', on_delete=django.db.models.deletion.CASCADE, to='core.orders'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='productcode',
            field=models.ForeignKey(db_column='ProductCode', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brandname',
            field=models.ForeignKey(db_column='BrandName', on_delete=django.db.models.deletion.CASCADE, to='core.brand'),
        ),
    ]
