# Generated by Django 3.1.4 on 2022-03-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20220329_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.CharField(db_column='IMG', max_length=200, null=True),
        ),
    ]
