# Generated by Django 3.1.4 on 2022-03-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20220329_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.CharField(db_column='IMG', default='placeholder.png', max_length=200),
        ),
    ]
