# Generated by Django 3.1.4 on 2022-03-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20220329_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderdate',
            field=models.DateField(db_column='OrderDate', default='2022-03-30'),
        ),
        migrations.AlterField(
            model_name='product',
            name='createdate',
            field=models.DateField(db_column='CreateDate', default='2022-03-30'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(db_column='IMG', default='placeholder.png', max_length=200, upload_to=''),
        ),
    ]
