# Generated by Django 3.1.4 on 2022-04-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20220408_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='unread',
            field=models.BooleanField(db_column='unread', default=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderdate',
            field=models.DateField(db_column='OrderDate', default='2022-04-13'),
        ),
        migrations.AlterField(
            model_name='product',
            name='createdate',
            field=models.DateField(db_column='CreateDate', default='2022-04-13'),
        ),
    ]
