# Generated by Django 3.1.4 on 2022-04-13 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20220413_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='unread',
        ),
    ]
