# Generated by Django 3.1.4 on 2022-04-15 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20220415_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetails',
            name='productcode',
            field=models.ForeignKey(db_column='ProductID', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
