# Generated by Django 3.1.4 on 2022-04-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20220417_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdetails',
            old_name='productcode',
            new_name='productid',
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderdate',
            field=models.DateField(db_column='OrderDate', default='2022-04-18'),
        ),
        migrations.AlterField(
            model_name='product',
            name='createdate',
            field=models.DateField(db_column='CreateDate', default='2022-04-18'),
        ),
    ]
