# Generated by Django 3.1.4 on 2022-04-18 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20220418_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='productcode',
            new_name='productid',
        ),
    ]
